services:
  sqlserver:
    build: .
    container_name: sqlserver-bacpac
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SqlServer@6"
      MSSQL_PID: "Developer"
    command: /opt/mssql/bin/sqlservr
    volumes:
      - ./backup.bacpac:/backup.bacpac:ro
    networks:
      - db_etl

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: Postgres@6
      POSTGRES_DB: pro4tech
    ports:
    - "5432:5432"
    networks:
      - db_etl
  
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Mongo6
    ports:
    - "27017:27017"  
    networks:
      - db_etl

networks:
  db_etl:
    external: true

